### ISSUE TITLE
Could not find org.theta4j:theta-web-api:1.5.0.

### ISSUE THREAD

**Issue by myunghyun-mk** [theta4j/theta-web-api#2]
Could not find org.theta4j:theta-web-api:1.5.0.

dependencies {
    ...
    implementation 'org.theta4j:theta-web-api:1.5.0' // insert this line
}

The above code gives an error
Where is 1.5.0?
1.4.0 exists
There is no 1.5.0.

**Comment by shrhdk** [comment]
Sorry. I published v1.5.0 just now.
